<?cs if:doc.type != "overview"?>
<div id="footer">
<div class="footer">
<div style="margin:0 0 10px 200px;">Copyright (C) 2013 Orange S.A.,</br> Generated by <a href="http://code.google.com/p/doclava/">Doclava</a>.</div>
</div>
</div> <!-- end footer -->
<?cs /if ?>
